### ISSUE TITLE
Unable to generate output

### ISSUE THREAD

**Issue by umarmuzammil** [zfergus/seam-erasure#3]
Hi, I am using **Python 2.7.16**.  When I build it using flask and hit submit with default values with a mesh and png texture.  I get this error Error: Unable to erase the texture (_erase_seam() got an unexpected keyword argument 'display_energy_file'_).

![image](https://user-images.githubusercontent.com/14996063/73062413-28f3dc00-3ebe-11ea-9a8c-c3ac8d6aad4f.png)

**Comment by zfergus** [comment]
Thanks for trying out Seam Erasure. I just pushed a fix. Let me know if it doesn't work for you.

**Comment by umarmuzammil** [comment]
Flask working now. I must say this is totally amazing. seams are such boring process and this tool solves the problem for real.  
Though web version did work but got performance hit when I tried using 8K texture, everything got stuck for an hour before I restarted and switched to CLI version.  

Here's another issue with command line.
![image](https://user-images.githubusercontent.com/14996063/73124681-cbe04f00-3fbf-11ea-8742-38beb375f6e3.png)

I did search for it. I guess this could work. 
https://stackoverflow.com/questions/20781730/ipython-no-module-named-importerror

**Comment by zfergus** [comment]
Do you have `cvxopt` installed? I didn't put it in the `requirements.txt` because I think it is more optional (normally use Scipy's sparse solver works well but is a bit slower). Try installing CVXOPT with `pip install cvxopt` (assuming you are using `pip`). 

You are right that the Flask based interface can hang for larger textures with no indication of progress. 

One word of warning, you may have difficulties with 4K and up textures as the sparse linear solver uses a lot of memory for those large textures. It's a problem that I've been needing to fix for a while. I am using a direct linear solver. An iterative solver might work better (memory-wise and maybe time-wise). I'll see what I can do, but it may be a while before I have time to look into it.

**Comment by umarmuzammil** [comment]
Its working with sparse linear solver. but you are right, its slow. I installed cvxopt but I think the code breaks unless you install specific binaries of numpy+mkl, cvxopt, cvxply before it uses sparse solver.  

4k, 8k textures are common in CG industry these days and this tool has so much potential. It can be use to create seamless pattern of any texture on a plane just by tilling uvs.
I've added this to my watchlist. Looking forward to see this work with bigger resolutions.  Thank you. 

Here's my output screenshot.
![image](https://user-images.githubusercontent.com/14996063/73134345-62138400-4057-11ea-908b-eff398950968.png)
